package lt.vu.usecases.mybatis.model;

public class Club {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLUB.ID
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLUB.TITLE
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLUB.ID
     *
     * @return the value of PUBLIC.CLUB.ID
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLUB.ID
     *
     * @param id the value for PUBLIC.CLUB.ID
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLUB.TITLE
     *
     * @return the value of PUBLIC.CLUB.TITLE
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLUB.TITLE
     *
     * @param title the value for PUBLIC.CLUB.TITLE
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }
}