package lt.vu.usecases.mybatis.model;

public class SupporterPlayer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUPPORTER_PLAYER.SUPPORTERS_ID
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    private Integer supportersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUPPORTER_PLAYER.PLAYERS_ID
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    private Integer playersId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUPPORTER_PLAYER.SUPPORTERS_ID
     *
     * @return the value of PUBLIC.SUPPORTER_PLAYER.SUPPORTERS_ID
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    public Integer getSupportersId() {
        return supportersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUPPORTER_PLAYER.SUPPORTERS_ID
     *
     * @param supportersId the value for PUBLIC.SUPPORTER_PLAYER.SUPPORTERS_ID
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    public void setSupportersId(Integer supportersId) {
        this.supportersId = supportersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUPPORTER_PLAYER.PLAYERS_ID
     *
     * @return the value of PUBLIC.SUPPORTER_PLAYER.PLAYERS_ID
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    public Integer getPlayersId() {
        return playersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUPPORTER_PLAYER.PLAYERS_ID
     *
     * @param playersId the value for PUBLIC.SUPPORTER_PLAYER.PLAYERS_ID
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    public void setPlayersId(Integer playersId) {
        this.playersId = playersId;
    }
}