package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.Club;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ClubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLUB
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLUB
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    int insert(Club record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLUB
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    Club selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLUB
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    List<Club> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLUB
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    int updateByPrimaryKey(Club record);
}