package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.SupporterPlayer;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SupporterPlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUPPORTER_PLAYER
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    int insert(SupporterPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUPPORTER_PLAYER
     *
     * @mbg.generated Tue Apr 17 21:44:50 EEST 2018
     */
    List<SupporterPlayer> selectAll();
}